SELECT DATE_ADD(NOW(), INTERVAL -4 YEAR) AS four_years_ago,
DATE_ADD(NOW(), INTERVAL 11 DAY) AS eleven_days_ahead,
DATE_SUB(NOW(), INTERVAL 10 YEAR) AS ten_years_ago,
DATEDIFF(NOW(), DATE_SUB(NOW(), INTERVAL 1 YEAR))