SHOW VARIABLES LIKE 'transaction_isolation';
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ


-- Types of Isolation
-- READ UNCOMMITTED
-- READ COMMITTED
-- REPEATABLE READ
-- SERIALIZABLE